version: "3"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: apps/my-app/Dockerfile
    command: npm run start:debug
    user: root
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app:ro
      - /usr/src/app/node_modules
      - /usr/src/app/dist
